"""initial

Revision ID: 07044ea3c79d
Revises: 
Create Date: 2022-06-14 16:21:06.675243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07044ea3c79d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_created_at'), 'urls', ['created_at'], unique=False)
    op.create_table('url_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_stats')
    op.drop_index(op.f('ix_urls_created_at'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
